# -*- coding: utf-8 -*-
"""Analyzing_KGF_2_movie_review_with_LLMs_GenAIs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvjWtWjGum7WCJkgsovpP5tiwnh2AMns

Note: Run this notebook in Google Colab

This notebook is essentially an end-to-end NLP pipeline using Hugging Face Transformers on Dhurandhar 2 movie reviews.

Key NLP Tasks Demonstrated
* Sentiment Analysis → Positive/Negative classification
* Machine Translation → English → Spanish
* Question Answering → Extract information from reviews
* Text Summarization → Generate concise review summaries
* Model Evaluation → Accuracy, F1 Score, BLEU Score

# Insert necessary Libraries
"""

!pip install transformers evaluate
!pip install -U transformers sentencepiece sacremoses
!pip install evaluate

"""# Check the version of Trnasformation"""

import transformers
print(transformers.__version__)

"""# Ingest dataset for sample reviews, also, segregate Review and Label columns"""

import pandas as pd
import torch

# Load the car reviews dataset
file_path = "/content/netflix movie KGF 2-2.csv"
df = pd.read_csv(file_path, delimiter=";")

# Put the car reviews and their associated sentiment labels in two lists
reviews = df['Review'].tolist()
real_labels = df['Class'].tolist()

"""# create a pipeline for the task sentiment-analysis using LLM Model"""

# Instruction 1: sentiment classification


# Load a sentiment analysis LLM into a pipeline
from transformers import pipeline
classifier = pipeline('sentiment-analysis', model='distilbert-base-uncased-finetuned-sst-2-english')

# The Pipeline is a simple but powerful inference API that is readily
# available for a variety of machine learning tasks with any model from the Hugging Face Hub.

# This pipeline performs text classification on a given input and determines if its a
# positive or negative sentiment. You can pass
# multiple texts to the same pipeline, which will be processed and passed through the model together as a batch.

# distilbert-base-uncased-finetuned-sst-2-english: This model is a fine-tune checkpoint of DistilBERT-base-uncased,
# fine-tuned on SST-2.

# Developed by: Hugging Face
# Model Type: Text Classification

# This model can be used for topic classification. You can use the raw model for either masked language
# modeling or next sentence prediction, but it's mostly intended to be fine-tuned on a downstream task.

"""# Check sample review"""

print(reviews)

"""# Print the respective label"""

print(real_labels)

"""# Custom review provided by User"""

reviews_example="The movie was fantastic!"
predicted_labels1 = classifier(reviews_example)
print(predicted_labels1 )

"""# Load accuracy and F1 score metrics for given dataset"""

# Perform inference on the movie reviews and display prediction results
predicted_labels = classifier(reviews)
for review, prediction, label in zip(reviews, predicted_labels, real_labels):
    print(f"Review: {review}\nActual Sentiment: {label}\nPredicted Sentiment: {prediction['label']} (Confidence: {prediction['score']:.4f})\n")

# Load accuracy and F1 score metrics
import evaluate
# Evaluate is a library that makes evaluating
# and comparing models and reporting their performance easier and more standardized.
accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

"""# Map categorical sentiment labels into integer labels"""

references = [1 if label == "POSITIVE" else 0 for label in real_labels]
predictions = [1 if label['label'] == "POSITIVE" else 0 for label in predicted_labels]

# Calculate accuracy and F1 score
accuracy_result_dict = accuracy.compute(references=references, predictions=predictions)
accuracy_result = accuracy_result_dict['accuracy']
f1_result_dict = f1.compute(references=references, predictions=predictions)
f1_result = f1_result_dict['f1']
print(f"Accuracy: {accuracy_result}")
print(f"F1 result: {f1_result}")

"""


*   Sample Review: KGF 2 is an amazing movie with powerful action and excellent performance.
*   Sentiment Analysis: POSITIVE

"""

# Sentiment Analysis for a Sample Movie Review
# Provide your own sample review below
sample_review = "KGF 2 is an amazing movie with powerful action and excellent performance."

# Generate sentiment prediction using the previously loaded classifier
sentiment_result = classifier(sample_review)

# Extract sentiment label: POSITIVE or NEGATIVE
sentiment = sentiment_result[0]['label']

print("Sample Review:", sample_review)
print("Sentiment Analysis:", sentiment)

"""# Project ends here

############################################################################################
"""